services:
  - type: web
    name: kktcx
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: kktcx
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: https://kktcx.com,https://www.kktcx.com
      - key: REACT_APP_BACKEND_URL
        value: https://kktcx.com
